spring:
  datasource:
    url: jdbc:sqlite:/home/machine/MeanMachines/MeanStreamMachine/resources/database/meanstreammachine.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
logging:
  level:
    root: info

storage:
  media-dir: /home/machine/MeanMachines/MeanStreamMachine/resources/media

exceptions:
  STACK_VERBOSE: false