server:
  servlet:
    context-path: /meanstream
  port: 60185

spring:
  application:
    name: meanstreammachine
  jpa:
    show-sql: true
logging:
  level:
    root: info

exceptions:
  STORAGE_RESPONSE: The server encountered an error processing the request and could not recover