spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meanmachines
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
logging:
  level:
    root: info

storage:
  media-dir: #TODO

exceptions:
  STACK_VERBOSE: false