spring:
  datasource:
    url: jdbc:postgresql://192.168.0.128:5432/template1
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: info

storage:
  media-dir: /home/machine/MeanMachines/MeanStreamMachine/resources/media

exceptions:
  STACK_VERBOSE: false